### ISSUE TITLE
AtrousConvolution2D assertion error setting atrious rate.

### ISSUE THREAD

**Issue by Accentax** [usernaamee/keras-wavenet#4]
I’m getting an assertion error for AtrousConvolution2D setting the atrous rate. Are you getting this?

Traceback (most recent call last):
  File "simple-generative-model-regressor.py", line 83, in <module>
    model = get_basic_generative_model(frame_size)
  File "simple-generative-model-regressor.py", line 30, in get_basic_generative_model
    l1a, l1b = wavenetBlock(10, 5, 2, 1, 3)(input)
  File "simple-generative-model-regressor.py", line 16, in f
    border_mode='same')(input)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 515, in **call**
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 573, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 663, in call
    filter_dilation=self.atrous_rate)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1520, in conv2d

**Comment by usernaamee** [comment]
No, I am not getting this error.
I am using the latest versions of both theano & keras pulled directly from github.

**Comment by Accentax** [comment]
I tried with theano, that worked. The error seems to be and integration issue between keras and tensorflow.

**Comment by usernaamee** [comment]
Ohh, ok.
Thanks.
